# Taps
tap 'caskroom/cask'
tap 'caskroom/fonts'
tap 'caskroom/versions'
tap 'homebrew/bundle'

# Install GNU utilities
brew 'coreutils'
brew 'moreutils'
brew 'findutils'
brew 'tree'
brew 'wget'
brew 'grep'
brew 'openssh'
brew 'osxutils'

# Update git and install utilities
brew 'git'
brew 'git-extras'
brew 'hub'
brew 'wifi-password'
brew 'httpie'
brew 'ccat'
brew 'highlight'

# Intall shells
brew 'zsh'
brew 'zsh-completions'
brew 'fish'
brew 'bash'

# Dev tools
brew 'xcenv' # Install Xcode helpers
brew 'nvm' # Node and Rails
brew 'python'
brew 'swiftlint'
brew 'swiftgen'
brew 'cocoapods'
brew 'carthage'
brew 'chisel'
brew 'rbenv'
brew 'ruby-build'
brew 'sshrc' # ssh thah loads rc files on remote hosts
brew 'htop'
brew 'tldr'

# Settings backup
brew 'mackup' 

# Casks
cask '1password'
cask 'dropbox'
cask 'imageoptim'
cask 'imagealpha'
cask 'iterm2'
cask 'visual-studio-code'
cask 'google-chrome'
cask 'tower2'
cask 'kaleidoscope'
cask 'spotify'
cask 'alfred'
cask 'realm-browser'
cask 'nvalt'
cask 'tunnelblick-beta'
cask 'insomnia'
cask 'macvim'
cask 'osxfuse'
cask 'hyper'
cask 'cyberduck'
cask 'sip'
cask 'shuttle'
cask 'rocket'
cask 'vanilla'

# SSH File System
brew 'sshfs' #this has to be installed after osxfuse

# Quicklook Plugins
cask 'qlcolorcode'
cask 'qlstephen'
cask 'qlmarkdown'
cask 'quicklook-json'
cask 'qlprettypatch'
cask 'quicklook-csv'
cask 'betterzip'
cask 'qlimagesize'
cask 'webpquicklook'
cask 'suspicious-package'
cask 'provisionql'

# Fonts
cask 'font-source-code-pro'
cask 'font-inconsolata'
cask 'font-hack'
cask 'font-anonymous-pro'

# Mac App Store Apps
mas 'Tweetbot', id: 557168941
mas 'Expressions', id: 913158085
mas '1Blocker', id: 1107421413
mas 'DayOne', id: 1055511498
mas 'aText', id: 488566438
mas '2Do', id: 477670270
mas 'Magnet', id: 441258766
mas 'Marked 2', id: 890031187
mas 'Slack', id:803453959
mas 'Dropzone 3', id:695406827
